package com.pojo;

// Generated Mar 20, 2019 5:37:18 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Attendance generated by hbm2java
 */
public class Attendance implements java.io.Serializable {

	private Integer aid;
	private Employee employee;
	private String status;
	private Date adate;

	public Attendance() {
	}

	public Attendance(Employee employee, String status, Date adate) {
		this.employee = employee;
		this.status = status;
		this.adate = adate;
	}

	public Integer getAid() {
		return this.aid;
	}

	public void setAid(Integer aid) {
		this.aid = aid;
	}

	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Date getAdate() {
		return this.adate;
	}

	public void setAdate(Date adate) {
		this.adate = adate;
	}

}
