package com.pojo;

// Generated Mar 20, 2019 5:37:18 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Billing generated by hbm2java
 */
public class Billing implements java.io.Serializable {

	private Integer billid;
	private Manageproduct manageproduct;
	private Customer customer;
	private Integer invoiceno;
	private Date invoicedate;
	private String warranty;
	private Integer quantity;
	private Double unitprice;
	private String taxtype;
	private Integer taxvalue;
	private Double totalamount;
	private Double totaltax;
	private Integer discount;
	private Double netamount;

	public Billing() {
	}

	public Billing(Manageproduct manageproduct, Customer customer, Integer invoiceno, Date invoicedate,
			String warranty, Integer quantity, Double unitprice, String taxtype, Integer taxvalue, Double totalamount,
			Double totaltax, Integer discount, Double netamount) {
		this.manageproduct = manageproduct;
		this.customer = customer;
		this.invoiceno = invoiceno;
		this.invoicedate = invoicedate;
		this.warranty = warranty;
		this.quantity = quantity;
		this.unitprice = unitprice;
		this.taxtype = taxtype;
		this.taxvalue = taxvalue;
		this.totalamount = totalamount;
		this.totaltax = totaltax;
		this.discount = discount;
		this.netamount = netamount;
	}

	public Integer getBillid() {
		return this.billid;
	}

	public void setBillid(Integer billid) {
		this.billid = billid;
	}

	public Manageproduct getManageproduct() {
		return this.manageproduct;
	}

	public void setManageproduct(Manageproduct manageproduct) {
		this.manageproduct = manageproduct;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public Integer getInvoiceno() {
		return this.invoiceno;
	}

	public void setInvoiceno(Integer invoiceno) {
		this.invoiceno = invoiceno;
	}

	public Date getInvoicedate() {
		return this.invoicedate;
	}

	public void setInvoicedate(Date invoicedate) {
		this.invoicedate = invoicedate;
	}

	public String getWarranty() {
		return this.warranty;
	}

	public void setWarranty(String warranty) {
		this.warranty = warranty;
	}

	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	public Double getUnitprice() {
		return this.unitprice;
	}

	public void setUnitprice(Double unitprice) {
		this.unitprice = unitprice;
	}

	public String getTaxtype() {
		return this.taxtype;
	}

	public void setTaxtype(String taxtype) {
		this.taxtype = taxtype;
	}

	public Integer getTaxvalue() {
		return this.taxvalue;
	}

	public void setTaxvalue(Integer taxvalue) {
		this.taxvalue = taxvalue;
	}

	public Double getTotalamount() {
		return this.totalamount;
	}

	public void setTotalamount(Double totalamount) {
		this.totalamount = totalamount;
	}

	public Double getTotaltax() {
		return this.totaltax;
	}

	public void setTotaltax(Double totaltax) {
		this.totaltax = totaltax;
	}

	public Integer getDiscount() {
		return this.discount;
	}

	public void setDiscount(Integer discount) {
		this.discount = discount;
	}

	public Double getNetamount() {
		return this.netamount;
	}

	public void setNetamount(Double netamount) {
		this.netamount = netamount;
	}

}
